"use client";
import { useEffect, useState } from "react";
import { Check, Instagram, Linkedin, LoaderCircle, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui";
import { useAuth } from "@/components/auth-provider";
import { useAppStore } from "@/components/app-store";

type LiveConnection={platform:string;status:string;accountName?:string;accountType?:string;updatedAt?:string};
export default function Connections(){
 const {user,configured}=useAuth();const store=useAppStore();const [connections,setConnections]=useState<LiveConnection[]>([]);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState("");
 async function authHeaders(){return {Authorization:`Bearer ${await user?.getIdToken()}`,"Content-Type":"application/json"}}
 useEffect(()=>{async function load(){if(!user)return;try{const response=await fetch("/api/connections",{headers:{Authorization:`Bearer ${await user.getIdToken()}`}});if(response.ok)setConnections((await response.json()).connections)}catch{/* status remains configuration required */}}void load();const query=new URLSearchParams(window.location.search);if(query.get("connected"))setMessage(`${query.get("connected")} connected successfully.`);if(query.get("error"))setMessage("Connection could not be completed. Check developer-app permissions and callback URLs.")},[user]);
 async function connect(provider:"meta"|"linkedin"){if(!user){setMessage("Sign in with Firebase before connecting a social account.");return}setBusy(provider);try{const response=await fetch(`/api/oauth/${provider}/start`,{method:"POST",headers:await authHeaders(),body:JSON.stringify({workspaceId:store.workspaceId})});const result=await response.json();if(!response.ok)throw new Error(result.error);window.location.assign(result.url)}catch(error){setMessage(error instanceof Error?error.message:"Could not start connection.");setBusy(null)}}
 async function disconnect(platform:"instagram"|"linkedin"){if(!user||!confirm(`Disconnect ${platform}?`))return;setBusy(platform);const response=await fetch(`/api/connections?provider=${platform}`,{method:"DELETE",headers:await authHeaders()});setBusy(null);if(response.ok){setConnections(v=>v.filter(c=>c.platform!==platform));setMessage(`${platform} disconnected.`)}else setMessage("Could not disconnect this account.")}
 const cards=[{platform:"instagram" as const,provider:"meta" as const,name:"Instagram",detail:"Professional account",Icon:Instagram,requirement:"Requires an Instagram Business or Creator account linked to a Facebook Page."},{platform:"linkedin" as const,provider:"linkedin" as const,name:"LinkedIn",detail:"Member or organization",Icon:Linkedin,requirement:"Member posting works with w_member_social. Company Pages require approved organization access."}];
 return <div className="page simple-connections"><div className="page-header"><div><span className="eyebrow">Workspace</span><h1>Connect your accounts</h1><p>Authorize once. OPSNORA Social will publish only the content you schedule.</p></div></div>{message&&<div className="inline-notice success"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}{!configured&&<div className="inline-notice error">Firebase must be configured before live social connections can be stored securely.</div>}<div className="integration-grid">{cards.map(card=>{const connection=connections.find(c=>c.platform===card.platform);const loading=busy===card.provider||busy===card.platform;return <article className="integration-card simple-card" key={card.platform}><header><span className={`integration-logo ${card.platform}`}><card.Icon size={26}/></span><div><h2>{card.name}</h2><p>{card.detail}</p></div><span className={`connection-state ${connection?"connected":"expired"}`}>{connection?"Connected":"Not connected"}</span></header><p className="connection-requirement">{card.requirement}</p>{connection&&<div className="connected-summary"><Check size={17}/><div><strong>{connection.accountName}</strong><small>{connection.accountType} · Secure token stored</small></div></div>}<footer><Button disabled={loading||!configured} onClick={()=>connect(card.provider)}>{loading?<LoaderCircle className="spin" size={15}/>:null}{connection?"Reconnect":`Connect ${card.name}`}</Button>{connection&&<Button variant="ghost" onClick={()=>disconnect(card.platform)}>Disconnect</Button>}</footer></article>})}</div><section className="setup-checklist"><div><ShieldCheck size={22}/><h2>One-time setup required</h2></div><ol><li><span>1</span><p><strong>Create developer apps</strong>Register OPSNORA Social in Meta for Developers and LinkedIn Developer Portal.</p></li><li><span>2</span><p><strong>Add callback URLs</strong>Copy the exact HTTPS callback URLs from your environment configuration.</p></li><li><span>3</span><p><strong>Request publishing permissions</strong>Complete platform verification and App Review for the permissions you need.</p></li><li><span>4</span><p><strong>Add server credentials</strong>Place client IDs and secrets only in <code>.env.local</code>, then restart the app.</p></li></ol></section></div>
}
