"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { brand } from "@/lib/config";
import { useAuth } from "@/components/auth-provider";

function friendlyError(error:unknown){const code=typeof error==="object"&&error&&"code" in error?String(error.code):"";if(code.includes("invalid-credential")||code.includes("wrong-password")||code.includes("user-not-found"))return "Invalid email or password.";if(code.includes("email-already-in-use"))return "An account already exists with this email.";if(code.includes("weak-password"))return "Please choose a stronger password.";if(code.includes("too-many-requests"))return "Too many attempts. Please try again later.";if(code.includes("network-request-failed"))return "Unable to connect. Check your internet connection and try again.";if(code.includes("invalid-email"))return "Enter a valid email address.";if(error instanceof Error&&error.message.startsWith("Firebase configuration"))return "Authentication is temporarily unavailable. Please contact support.";return "Authentication could not be completed. Please try again."}
function safeNext(value:string|null){if(!value||!value.startsWith("/")||value.startsWith("//")||value.includes("\\"))return "/";try{const url=new URL(value,"http://internal");return url.origin==="http://internal"?`${url.pathname}${url.search}${url.hash}`:"/"}catch{return "/"}}

export default function Login(){
 const router=useRouter();const auth=useAuth();const [mode,setMode]=useState<"login"|"forgot"|"signup">("login");const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [msg,setMsg]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [nextPath,setNextPath]=useState("/");
 useEffect(()=>{const next=safeNext(new URLSearchParams(window.location.search).get("next"));setNextPath(next);if(auth.isAuthenticated)router.replace(next)},[auth.isAuthenticated,router]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setMsg("");setBusy(true);try{if(mode==="forgot"){await auth.resetPassword(email);setMsg("Password reset email sent. Check your inbox.");return}if(mode==="signup")await auth.signUp(name,email,password);else await auth.signIn(email,password);router.replace(nextPath)}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 return <main className="auth-page"><section className="auth-brand"><div className="auth-brand-inner"><span className="brand-mark">O</span><p>An OPSNORA product</p><h1>Bring clarity to your social media operations.</h1><p>Plan, schedule and manage every post from one focused workspace.</p><div className="auth-quote">Secure authentication and private media storage powered by Firebase.<small>OPSNORA Social</small></div></div></section><section className="auth-form"><div><span className="auth-logo">{brand.product}</span><h2>{mode==="login"?"Welcome back":mode==="forgot"?"Reset password":"Create your account"}</h2><p>{mode==="login"?"Sign in to continue to your workspace.":mode==="forgot"?"Enter your email to receive a secure reset link.":"Create a protected OPSNORA Social account."}</p>{!auth.configured&&<div className="inline-notice error">{auth.configurationError}</div>}{error&&<div className="inline-notice error">{error}</div>}{msg&&<div className="inline-notice success">{msg}</div>}<form onSubmit={submit}>{mode==="signup"&&<label className="field"><span>Full name</span><input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label className="field"><span>Email address</span><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" required placeholder="you@company.com"/></label>{mode!=="forgot"&&<label className="field"><span>Password</span><input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} autoComplete={mode==="login"?"current-password":"new-password"} required placeholder="At least 6 characters"/></label>}{mode==="login"&&<div className="form-between"><span>Secure Firebase session</span><button type="button" className="text-button" onClick={()=>setMode("forgot")}>Forgot password?</button></div>}<button className="button button-primary auth-submit" disabled={busy||!auth.configured} type="submit">{busy?"Please wait…":mode==="login"?"Sign in":mode==="forgot"?"Send reset link":"Create account"}</button></form>{!auth.configured&&process.env.NEXT_PUBLIC_DEMO_MODE==="true"&&<button className="button button-secondary auth-submit demo-access" onClick={()=>{auth.enableDemoAccess();router.replace(nextPath)}}>Continue in local demo mode</button>}<p className="signup-copy">{mode==="login"?"New to OPSNORA Social? ":"Already have an account? "}<button className="text-button" onClick={()=>{setMode(mode==="login"?"signup":"login");setError("");setMsg("")}}>{mode==="login"?"Create an account":"Sign in"}</button></p></div></section></main>
}
