"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithEmailAndPassword, updateProfile } from "firebase/auth";
import { brand } from "@/lib/config";
import { firebaseAuth } from "@/lib/firebase";
import { useAuth } from "@/components/auth-provider";

function friendlyError(error: unknown){const code=typeof error==="object"&&error&&"code" in error?String(error.code):"";if(code.includes("invalid-credential"))return "Incorrect email or password.";if(code.includes("email-already-in-use"))return "An account already exists for this email.";if(code.includes("weak-password"))return "Use a password with at least 6 characters.";if(code.includes("too-many-requests"))return "Too many attempts. Please wait and try again.";return "Authentication could not be completed. Please try again."}

export default function Login(){
 const router=useRouter();const {user,configured,enableDemoAccess}=useAuth();const [mode,setMode]=useState<"login"|"forgot"|"signup">("login");const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [msg,setMsg]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{if(user)router.replace("/")},[user,router]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setMsg("");if(!firebaseAuth){setError("Firebase is not configured yet. Add the Firebase variables to .env.local.");return}setBusy(true);try{if(mode==="forgot"){await sendPasswordResetEmail(firebaseAuth,email);setMsg("Password reset email sent. Check your inbox.");return}if(mode==="signup"){const credential=await createUserWithEmailAndPassword(firebaseAuth,email,password);if(name.trim())await updateProfile(credential.user,{displayName:name.trim()});}else await signInWithEmailAndPassword(firebaseAuth,email,password);router.replace("/")}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 return <main className="auth-page"><section className="auth-brand"><div className="auth-brand-inner"><span className="brand-mark">O</span><p>An OPSNORA product</p><h1>Bring clarity to your social media operations.</h1><p>Plan, schedule and manage every post from one focused workspace.</p><div className="auth-quote">Secure authentication and private media storage powered by Firebase.<small>OPSNORA Social</small></div></div></section><section className="auth-form"><div><span className="auth-logo">{brand.product}</span><h2>{mode==="login"?"Welcome back":mode==="forgot"?"Reset password":"Create your account"}</h2><p>{mode==="login"?"Sign in to continue to your workspace.":mode==="forgot"?"Enter your email to receive a secure reset link.":"Create a protected OPSNORA Social account."}</p>{!configured&&<div className="inline-notice error">Firebase configuration required. Login remains locked until setup is complete.</div>}{error&&<div className="inline-notice error">{error}</div>}{msg&&<div className="inline-notice success">{msg}</div>}<form onSubmit={submit}>{mode==="signup"&&<label className="field"><span>Full name</span><input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label className="field"><span>Email address</span><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" required placeholder="you@company.com"/></label>{mode!=="forgot"&&<label className="field"><span>Password</span><input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} autoComplete={mode==="login"?"current-password":"new-password"} required placeholder="At least 6 characters"/></label>}{mode==="login"&&<div className="form-between"><label><input type="checkbox"/> Remember me</label><button type="button" className="text-button" onClick={()=>setMode("forgot")}>Forgot password?</button></div>}<button className="button button-primary auth-submit" disabled={busy||!configured} type="submit">{busy?"Please wait…":mode==="login"?"Sign in":mode==="forgot"?"Send reset link":"Create account"}</button></form>{!configured&&<button className="button button-secondary auth-submit demo-access" onClick={()=>{enableDemoAccess();router.replace("/")}}>Continue in local demo mode</button>}<p className="signup-copy">{mode==="login"?"New to OPSNORA Social? ":"Already have an account? "}<button className="text-button" onClick={()=>{setMode(mode==="login"?"signup":"login");setError("");setMsg("")}}>{mode==="login"?"Create an account":"Sign in"}</button></p></div></section></main>
}
