"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, CalendarClock, Check, Clock, CloudUpload, Image as ImageIcon, Instagram, Linkedin, Save, Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui";
import { useAppStore } from "@/components/app-store";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { isFirebaseStorageConfigured, uploadWorkspaceMedia } from "@/lib/firebase";

export default function CreatePost() {
  const store=useAppStore(); const router=useRouter(); const [editId,setEditId]=useState<string|null>(null); const fileRef=useRef<HTMLInputElement>(null); const {user,configured}=useAuth();
  const [platforms, setPlatforms] = useState({ instagram: true, linkedin: true });
  const [custom, setCustom] = useState(false);
  const [caption, setCaption] = useState("Precision in every profile. Built for the projects shaping tomorrow.\n\n#Engineering #BuiltToLast");
  const [linkedinCaption, setLinkedinCaption] = useState(caption);
  const [uploaded, setUploaded] = useState(true);
  const [preview, setPreview] = useState<"instagram" | "linkedin">("instagram");
  const [schedule, setSchedule] = useState<"now" | "later">("later");
  const [notice, setNotice] = useState("");
  const [date,setDate]=useState(new Date(Date.now()+86400000).toISOString().slice(0,10)); const [time,setTime]=useState("10:30"); const [title,setTitle]=useState("Building stronger structures"); const [mediaName,setMediaName]=useState("built-for-next.jpg"); const [mediaUrl,setMediaUrl]=useState(""); const [uploading,setUploading]=useState(false); const [uploadProgress,setUploadProgress]=useState(0);
  useEffect(()=>setEditId(new URLSearchParams(window.location.search).get("id")),[]);
  useEffect(()=>{if(!editId)return;const p=store.posts.find(x=>x.id===editId);if(p){setTitle(p.title);setCaption(p.caption);setLinkedinCaption(p.caption);setPlatforms({instagram:p.platforms.includes("instagram"),linkedin:p.platforms.includes("linkedin")});setUploaded(Boolean(p.mediaTone));const d=new Date(p.scheduledAt);setDate(d.toISOString().slice(0,10));setTime(`${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`)}},[editId,store.posts]);
  const activeCaption = custom && preview === "linkedin" ? linkedinCaption : caption;
  const canSchedule = uploaded && (platforms.instagram || platforms.linkedin) && activeCaption.trim();
  const validation = useMemo(() => platforms.instagram&&store.connections.instagram!=="connected" ? "Instagram is currently not connected. Reconnect it or deselect Instagram before scheduling." : "", [platforms.instagram,store.connections.instagram]);
  function persist(status:"draft"|"scheduled"|"published"){const selected=(Object.keys(platforms) as Array<keyof typeof platforms>).filter(p=>platforms[p]);const scheduledAt=schedule==="now"?new Date().toISOString():new Date(`${date}T${time}:00`).toISOString();const data={title:title.trim()||"Untitled post",caption,platforms:selected,scheduledAt,status,mediaTone:"navy",mediaUrl:mediaUrl||undefined};if(editId)store.updatePost(editId,data);else store.addPost(data);store.addNotification(status==="draft"?"Draft saved":"Post scheduled",`${data.title} was ${status==="draft"?"saved to drafts":"added to your publishing calendar"}.`);setNotice(status==="draft"?"Draft saved successfully.":"Post scheduled successfully.");setTimeout(()=>router.push(status==="draft"?"/drafts":"/calendar"),650)}
  function submit(){ if(validation)setNotice(validation);else if(!uploaded)setNotice("Add media before scheduling.");else persist(schedule==="now"?"published":"scheduled"); }
  async function selectFile(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(!file.type.match(/^image\/(jpeg|png|webp)$/)||file.size>10*1024*1024){setNotice("Please select a JPG, PNG or WebP image smaller than 10 MB.");return}setUploading(true);setMediaName(file.name);try{if(isFirebaseStorageConfigured&&user){const result=await uploadWorkspaceMedia(file,store.workspaceId,user.uid,setUploadProgress);setMediaUrl(result.url);setNotice("Image uploaded securely to Firebase Storage.")}else{setMediaUrl(URL.createObjectURL(file));setNotice(configured?"Image added for this session. Cloud media storage is not enabled.":"Image added in local demo mode.")}setUploaded(true)}catch{setNotice("Media upload could not be completed. Please try again.")}finally{setUploading(false);setUploadProgress(0)}}
  return <div className="page create-page"><div className="page-header"><div><span className="eyebrow">Content / {editId?"Edit post":"New post"}</span><h1>{editId?"Edit post":"Create post"}</h1><p>Compose once, tailor by platform and schedule with confidence.</p></div><div className="header-actions"><Button variant="secondary" onClick={()=>persist("draft")}><Save size={16}/> Save draft</Button><Button onClick={submit} disabled={!canSchedule}><CalendarClock size={16}/> {editId?"Update post":"Schedule post"}</Button></div></div>
    {notice && <div className={`inline-notice ${validation ? "error" : "success"}`}>{validation ? <AlertCircle size={17}/> : <Check size={17}/>}<span>{notice}</span><button onClick={() => setNotice("")}><X size={15}/></button></div>}
    <div className="composer-grid"><div className="composer">
      <section className="form-section"><div className="form-heading"><span>1</span><div><h2>Add media</h2><p>Upload an image for this post.</p></div></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={selectFile}/>{uploaded ? <div className="uploaded-media"><div className="media-preview">{mediaUrl?<img className="uploaded-image" src={mediaUrl} alt="Uploaded preview"/>:<div className="preview-art"><span>VIKRANT</span><strong>Built for<br/>what&apos;s next.</strong><small>ENGINEERED STEEL SOLUTIONS</small></div>}</div><div className="file-info"><span className="file-icon"><ImageIcon size={18}/></span><div><strong>{mediaName}</strong><small>{configured?"Stored in Firebase Storage":"Local demo media"}</small></div><button className="text-button" onClick={() => fileRef.current?.click()}>Replace</button><button className="icon-button" onClick={() => {setUploaded(false);setMediaUrl("")}}><X size={17}/></button></div></div> : <button className="dropzone" disabled={uploading} onClick={() => fileRef.current?.click()}><CloudUpload size={25}/><strong>{uploading?`Uploading ${uploadProgress}%`:"Choose an image"}</strong><span>JPG, PNG or WebP · Max 10 MB</span></button>}</section>
      <section className="form-section"><div className="form-heading"><span>2</span><div><h2>Choose platforms</h2><p>Select where this post should be published.</p></div></div><div className="platform-select"><button className={platforms.instagram ? "selected warning" : ""} onClick={() => setPlatforms(v => ({...v, instagram: !v.instagram}))}><span className="platform-logo instagram"><Instagram size={20}/></span><span><strong>Instagram</strong><small>@vikrantgroup · Connection expired</small></span><i>{platforms.instagram && <Check size={14}/>}</i></button><button className={platforms.linkedin ? "selected" : ""} onClick={() => setPlatforms(v => ({...v, linkedin: !v.linkedin}))}><span className="platform-logo linkedin"><Linkedin size={20}/></span><span><strong>LinkedIn</strong><small>Vikrant Group · Connected</small></span><i>{platforms.linkedin && <Check size={14}/>}</i></button></div></section>
      <section className="form-section"><div className="form-heading"><span>3</span><div><h2>Write your caption</h2><p>Keep one message or tailor it for each platform.</p></div></div><label className="field"><span>Internal post title</span><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100}/></label><div className="caption-mode"><button className={!custom ? "active" : ""} onClick={() => setCustom(false)}>Same caption everywhere</button><button className={custom ? "active" : ""} onClick={() => setCustom(true)}>Customize by platform</button></div><div className="ai-actions"><span><Sparkles size={14}/> Writing tools</span><button onClick={()=>setCaption(c=>`${c.trim()}\n\nDiscover what dependable engineering can make possible.`)}>Improve</button><button onClick={()=>setCaption(c=>c.replace(/!/g,".").replace(/\bawesome\b/gi,"exceptional"))}>Make professional</button><button onClick={()=>setCaption(c=>c.length>140?`${c.slice(0,137)}...`:c)}>Shorten</button><button onClick={()=>setCaption(c=>c.includes("#")?c:`${c.trim()}\n\n#Engineering #Innovation #OPSNORA`)}>Hashtags</button></div><label className="field"><span>{custom ? "Instagram caption" : "Caption"}</span><textarea value={caption} onChange={e => setCaption(e.target.value)} rows={6}/><small>{caption.length} / 2,200</small></label>{custom && <label className="field"><span>LinkedIn caption</span><textarea value={linkedinCaption} onChange={e => setLinkedinCaption(e.target.value)} rows={6}/><small>{linkedinCaption.length} / 3,000</small></label>}</section>
      <section className="form-section"><div className="form-heading"><span>4</span><div><h2>Choose when to publish</h2><p>Times are shown in your workspace timezone.</p></div></div><div className="schedule-toggle"><button className={schedule === "now" ? "active" : ""} onClick={() => setSchedule("now")}><span/><strong>Publish now</strong><small>Publish as soon as possible</small></button><button className={schedule === "later" ? "active" : ""} onClick={() => setSchedule("later")}><span/><strong>Schedule for later</strong><small>Choose a date and time</small></button></div>{schedule === "later" && <div className="date-row"><label><span>Date</span><input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>Time</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label><span>Timezone</span><select defaultValue="Asia/Kolkata"><option>Asia/Kolkata</option><option>UTC</option><option>America/New_York</option></select></label></div>}<p className="timezone-note"><Clock size={14}/> Your post will publish at <strong>{schedule==="now"?"as soon as possible":`${time} IST on ${date}`}</strong>.</p></section>
    </div><aside className="live-preview"><div className="preview-sticky"><div className="preview-title"><div><h2>Live preview</h2><p>Updates as you type</p></div><span>Preview</span></div><div className="preview-tabs"><button className={preview === "instagram" ? "active" : ""} onClick={() => setPreview("instagram")}><Instagram size={16}/> Instagram</button><button className={preview === "linkedin" ? "active" : ""} onClick={() => setPreview("linkedin")}><Linkedin size={16}/> LinkedIn</button></div><div className={`social-preview ${preview}`}><header><div className="social-avatar">VG</div><div><strong>{preview === "instagram" ? "vikrantgroup" : "Vikrant Group"}</strong><small>{preview === "instagram" ? "Sponsored" : "12,430 followers"}</small></div><b>•••</b></header><div className="social-image">{mediaUrl?<img className="uploaded-image" src={mediaUrl} alt="Post preview"/>:<div className="preview-art"><span>VIKRANT</span><strong>Built for<br/>what&apos;s next.</strong><small>ENGINEERED STEEL SOLUTIONS</small></div>}</div><div className="social-body">{preview === "instagram" && <div className="mock-actions">♡　⌁　◇ <span>♡</span></div>}<p><strong>{preview === "instagram" ? "vikrantgroup " : ""}</strong>{activeCaption}</p>{preview === "instagram" && <small>View all 12 comments</small>}</div></div>{validation && <div className="preview-warning"><AlertCircle size={16}/><p><strong>Instagram needs attention</strong><span>Reconnect before scheduling to this platform.</span></p></div>}</div></aside></div>
  </div>;
}
