"use client";
/* eslint-disable @next/next/no-img-element */
import { useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ImageIcon, Search, Trash2, Upload } from "lucide-react";
import { useAppStore } from "@/components/app-store";
import { useAuth } from "@/components/auth-provider";
import { isFirebaseStorageConfigured, uploadWorkspaceMedia } from "@/lib/firebase";

export default function Media(){
 const store=useAppStore();const {user,configured}=useAuth();const router=useRouter();const fileRef=useRef<HTMLInputElement>(null);const [query,setQuery]=useState("");const [type,setType]=useState("all");const [message,setMessage]=useState("");const [uploading,setUploading]=useState(false);const [progress,setProgress]=useState(0);
 const items=useMemo(()=>store.media.filter(m=>m.name.toLowerCase().includes(query.toLowerCase())&&(type==="all"||m.type===type)),[store.media,query,type]);
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]);if(!files.length)return;setUploading(true);try{for(const file of files){if(!file.type.startsWith("image/")||file.size>10*1024*1024)throw new Error(`${file.name}: only JPG, PNG or WebP under 10 MB is allowed.`);let url=URL.createObjectURL(file);if(isFirebaseStorageConfigured&&user){const result=await uploadWorkspaceMedia(file,store.workspaceId,user.uid,setProgress);url=result.url}store.addMedia({name:file.name,type:"image",size:`${(file.size/1024/1024).toFixed(1)} MB`,tone:"blue",dataUrl:url})}setMessage(isFirebaseStorageConfigured?`${files.length} file(s) uploaded securely to Firebase Storage.`:configured?`${files.length} file(s) added for this session. Cloud media storage is not enabled.`:`${files.length} file(s) added in local demo mode.`)}catch(error){setMessage(error instanceof Error?error.message:"Upload failed.")}finally{setUploading(false);setProgress(0);e.target.value=""}}
 return <div className="page"><div className="page-header"><div><span className="eyebrow">Assets</span><h1>Media library</h1><p>Upload, organize and reuse workspace media.</p></div><input ref={fileRef} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/><button className="button button-primary" disabled={uploading} onClick={()=>fileRef.current?.click()}><Upload size={16}/> {uploading?`Uploading ${progress}%`:"Upload media"}</button></div>{message&&<div className="inline-notice success">{message}<button onClick={()=>setMessage("")}>×</button></div>}<div className="toolbar"><label className="search-control"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search media"/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All media</option><option value="image">Images</option></select></div><div className="media-grid">{items.map(m=><article key={m.id}><div className={`media-tile thumb-${m.tone}`}>{m.dataUrl?<img className="uploaded-image" src={m.dataUrl} alt={m.name}/>:<ImageIcon size={25}/>}</div><div><strong>{m.name}</strong><small>{m.size} · {new Date(m.createdAt).toLocaleDateString()}</small></div><div className="media-actions"><button onClick={()=>router.push("/create")}>Use in post</button><button aria-label="Delete media" onClick={()=>{if(confirm(`Delete ${m.name}?`))store.deleteMedia(m.id)}}><Trash2 size={14}/></button></div></article>)}</div></div>
}
