"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import type { PostStatus } from "@/lib/types";
import { Badge, EmptyState } from "./ui";
import { PlatformIcon } from "./icons";
import { CalendarPlus, Copy, MoreHorizontal, Search, Trash2 } from "lucide-react";
import { format } from "date-fns";
import { useAppStore } from "./app-store";
import { useRouter } from "next/navigation";

export function PostList({ status, title, description }: { status: PostStatus; title: string; description: string }) {
  const [query, setQuery] = useState("");
  const [platform,setPlatform]=useState("all"); const [dateFilter,setDateFilter]=useState("all"); const [active,setActive]=useState<string|null>(null); const [message,setMessage]=useState(""); const store=useAppStore(); const router=useRouter();
  const posts = useMemo(() => store.posts.filter(p => {const age=Math.abs(new Date(p.scheduledAt).getTime()-Date.now());return p.status===status&&p.title.toLowerCase().includes(query.toLowerCase())&&(platform==="all"||p.platforms.includes(platform as "instagram"|"linkedin"))&&(dateFilter==="all"||(dateFilter==="week"&&age<=7*86400000)||(dateFilter==="month"&&age<=31*86400000))}), [query,status,platform,dateFilter,store.posts]);
  function action(kind:string,id:string){setActive(null);if(kind==="edit"){router.push(`/create?id=${id}`);return}if(kind==="duplicate"){store.duplicatePost(id);setMessage("Post duplicated and saved as a draft.")}if(kind==="delete"){if(confirm("Delete this post permanently?")){store.deletePost(id);setMessage("Post deleted.")}}if(kind==="cancel"){if(confirm("Cancel this scheduled post?")){store.updatePost(id,{status:"cancelled"});setMessage("Scheduled post cancelled.")}}if(kind==="schedule"){store.updatePost(id,{status:"scheduled",scheduledAt:new Date(Date.now()+86400000).toISOString()});setMessage("Draft scheduled for tomorrow.")}}
  return <div className="page"><div className="page-header"><div><span className="eyebrow">Content</span><h1>{title}</h1><p>{description}</p></div><Link href="/create" className="button button-primary">Create post</Link></div>
    {message&&<div className="inline-notice success"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}<div className="toolbar"><label className="search-control"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search posts"/></label><select aria-label="Platform" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">All platforms</option><option value="instagram">Instagram</option><option value="linkedin">LinkedIn</option></select><select aria-label="Date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}><option value="all">Any date</option><option value="week">This week</option><option value="month">This month</option></select></div>
    {posts.length ? <div className="table-card"><table><thead><tr><th>Post</th><th>Platforms</th><th>{status === "published" ? "Published" : "Scheduled for"}</th><th>Created by</th><th>Status</th><th></th></tr></thead><tbody>{posts.map(post => <tr key={post.id}><td><div className="post-cell"><div className={`thumb thumb-${post.mediaTone}`}/><div><strong>{post.title}</strong><small>{post.caption || "No caption yet"}</small></div></div></td><td><div className="platforms">{post.platforms.map(p => <span key={p} title={p}><PlatformIcon platform={p}/></span>)}</div></td><td><strong>{format(new Date(post.scheduledAt), "MMM d, yyyy")}</strong><small>{format(new Date(post.scheduledAt), "h:mm a")}</small></td><td>Aditya Garg</td><td><Badge status={post.status}/></td><td className="action-cell"><button className="icon-button" onClick={()=>setActive(active===post.id?null:post.id)}><MoreHorizontal size={18}/></button>{active===post.id&&<div className="action-menu"><button onClick={()=>action("edit",post.id)}>Edit</button><button onClick={()=>action("duplicate",post.id)}>Duplicate</button>{status==="draft"&&<button onClick={()=>action("schedule",post.id)}>Schedule tomorrow</button>}{status==="scheduled"&&<button onClick={()=>action("cancel",post.id)}>Cancel schedule</button>}<button className="danger" onClick={()=>action("delete",post.id)}>Delete</button></div>}</td></tr>)}</tbody></table></div> : <EmptyState icon={status === "draft" ? <Copy/> : status === "cancelled" ? <Trash2/> : <CalendarPlus/>} title={`No ${title.toLowerCase()} found`} description="Adjust your filters or create a new post to get started." action={<Link href="/create" className="button button-primary">Create post</Link>}/>} 
  </div>;
}
